### PR TITLE
add auto detect dynamic library by ext name & add os xml tag

### PR DESCRIPTION
**Pull request by orangetangerine**
add auto detect dynamic library by ext name & add os xml tag

### CODE REVIEW

**Comment by edvin** [comment]
Smart :) Thanks!

**Comment by orangetangerine** [comment]
Thanks. And I found that i did not specify my email address when push commits... I can not see my name in contributors 😂

**Comment by orangetangerine** [comment]
Thanks. I just realized I didn't specify any email address when pull request, so I can not see my name in contributors 😂

**Comment by orangetangerine** [comment]
Thanks. I just realized I didn't specify any email address when pull request, so I can not see my name in contributors 😂 .
I've corrected it and it would be my pleasure if you help me correct it in this two repo with a bash script 😂 
https://help.github.com/articles/changing-author-info/

**Comment by edvin** [comment]
I've never done that before and it looks scary - why don't you come up with yet another improvement and push it with your email configured? :) Hehe

**Comment by orangetangerine** [comment]
😆 sounds better 👍

**Pull request merged**
