### PR TITLE
Java 9 support for FXLauncher

### PR DESCRIPTION
**Pull request by abhinayagarwal**
This PR makes sure FXLauncher works on both 8 and 9 without Multi-Release Jar support

### CODE REVIEW

**Comment by edvin** [comment]
Thank you! Will merge after testing :)

**Comment by jmerle** [comment]
Do you have an estimate on when we can expect this PR to be merged?

**Comment by mordechaim** [comment]
Does this really work for Java 9? I don't see any changes in the classloading mechanism which will fail outright on Java 9.

**Comment by abhinayagarwal** [comment]
@mordechaim You may be right since this isn't tested.

@edvin seems to be busy. If someone is willing to test the changes and come back with feedback, we could move things faster.

**Comment by mordechaim** [comment]
Take a look at my spinoff from this project. Fully compatible with Java 9.

https://github.com/uptodate-project/uptodate

**Comment by edvin** [comment]
Absolutely, resolve the conflicts and I'll merge :) Sorry, this fell off my radar. Too busy with other projects these days, but if you'll resolve the conflicts I'll merge and do a new release right away.

**Comment by abhinayagarwal** [comment]
I can most probably look at it sometime this week.

**Comment by mordechaim** [comment]
An important note: JavaFX is no more part of the JDK. We'll have to use reflection to check if the Application class is present, print error message and exit if missing.

If it is present we have to reflectively invoke the launch method.

**Comment by mordechaim** [comment]
An important note: JavaFX is no more part of the JDK. We'll have to use reflection to check if the `javafx.application.Application` class is present, print error message and exit if missing. If it is present we have to reflectively invoke the launch method.

This has been done so [here](https://github.com/update4j/update4j/blob/master/src/main/java/org/update4j/service/DefaultLauncher.java#L69).

**Comment by xzel23** [comment]
I have looked into this and I think there are some things to consider:

 - Removing use of internal API should be done anyway and shouldn't break compatibility with Java 8.
 - To have a launcher that runs on Java 9+, both JAXB and JavaFX have to be on the classpath/module path.
 - This pull request in its current form produces a jar that's not compatible with JDK 8 anymore, so a little more work is needed.  
 - IMHO it should be enough to ensure that fxlauncher works on JDK 8 and JDK 11+ given that Java 9 and 10 are already obsolete and not LTS. Java 8 will still be around for a long time, so it should be supported, and Java 11 is the actual version and the first LTS release to include the module system.

I think the first point should in any case already be adresses. I might find the time in the next days to factor this out so that it is ready for merging. There is however still a small problem: I have not found a solution to set the application name as there doesn't seem to be any public API that exposes this functionality.

**Comment by edvin** [comment]
OK, good work :) If there isn't a public API to set the app name (sounds strage) we could give it a shot using reflection in a try/catch block perhaps?

**Comment by xzel23** [comment]
@edvin I think there's no publich API because it's called from the Application Launcher and it seems no one thought there'd be a need to use a custom launcher.

I have just come home from my holiday. I will try to find the time to create a patch containing those parts of the pull request that IMHO should be merged anyway and will work for both JDK 8 and 9+ (i.e. remove use of private API where a public API is available).

I'd then look at the remainder of the patch to make sure it is compatible with 8 and 9+.

**Comment by edvin** [comment]
@xzel23 OK, super :)

**Comment by abhinayagarwal** [comment]
Since @xzel23 is already looking into this, can this PR be declined?

**Pull request closed without merging**
