### PR TITLE
Added security by comparing signature hash with trusted certificate

### PR DESCRIPTION
**Pull request by mordechaim**
I've finally completed Issue #82 . I've placed great emphasis on backward compatibility, and I succeeded. 

Here are a few notes:

- If you pass a private key in ``LibraryFile``'s constructor or in ``CreateManifest::create``, a signature hash will be added to the manifest for the file.
- If the ``--cert`` option is passed into the launcher it will try to locate a ***local*** trusted certificate of the type ``X.509`` (which ideally should be planted in the local system when the launcher is first installed) and will check for integrity of each downloaded file *before writing it to the file-system*. If it matches, the file will be written.
- If the ``--cert`` option is not passed, it will ignore the signature and act as before this feature.
- If ``--cert`` is passed and the signature is missing, or signature verification fails for any reason, the update will be aborted. Whether it will be shown to the user or not depends on the ``--stopOnUpdateErrors`` option.

### CODE REVIEW

**Comment by mordechaim** [comment]
These commits I made after the first was a mistake, I reverted them to keep the pull request just on the signature thing.

**Comment by mordechaim** [comment]
I decided to allow writing to file even before verification. The initial reason I didn't want this was because if a hacker gives the same name to a cached legit file, it will overwrite it and then the launcher will delete it as "signature verification failed", causing to delete a (previously) legitimate file. This time I am using a temp file, so nothing gets overwritten.

**Comment by mordechaim** [comment]
I think I should put the byteArray propagation in an if statement `if(cert != null)` to reduce unnecessary work if no certificate is used. You can do it yourself, i'm currently working on something else.

Note also that i corrected the `FxClassCloader` typo, but didn't change the actual class name. Do it yourself too.

**Comment by gcstang** [comment]
Just my two cents but it felt more secure that you didn't write it to the system before validating it.   Do you want to write something that has been potentially been compromised to the system?

**Comment by mordechaim** [comment]
Thought the same, and did so in the begining. But then thought that on large files, the write delay will mess the progress bar. Anyway if you feel it's correct i'll change it back (with a little change)

**Comment by gcstang** [comment]
It could be just me but I'd feel better if it's never written to the target computer.  

I understand the progress bar would be "off" but maybe there is a way to fix that inside of fxlauncher so it takes this into consideration?

**Comment by mordechaim** [comment]
Will think of something about progress bar. Stay tuned

**Comment by mordechaim** [comment]
I got very busy now for a different project, so I close this pull request for now. Will see what I'll do in the future.

**Comment by mordechaim** [comment]
I got really busy for a different project so I close this pull request for now.

**Comment by edvin** [comment]
OK. Hope you find time to pick it back up again later!

**Pull request closed without merging**
